engines:
  pep8:
    enabled: true
  shellcheck:
    enabled: true
  markdownlint:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
ratings:
  paths:
    - "**.py"
    - "**.sh"
    - "README.md"
    - "scoreboard/html_static/css/style.css"
    - "scoreboard/html_static/js/dcss-scoreboard.js"
